#!/usr/bin/env python3
# Copyright (c) 2026 Go Yamamoto
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate led_driver_table.h (in this directory), the V65 V3's LED wiring for src/led_driver_spi.c, from the LED
table FILE (not in this repository; pass its path).

The table (4 bytes per VIA position, row * 15 + col, 120 entries, 480 bytes from the start of
the file) names each LED's driver chip (1 or 2) and the PWM channel of its red, green and
blue. The header lists, per chip, what each of the 192 channels drives: bits 1:0 the colour
(0 nothing, 1 red, 2 green, 3 blue), bits 5:2 the key's matrix column. The notice LED is the
Tab key's (row 2, col 0); the Caps Lock key's (row 3, col 0) shows the host's Caps Lock
(BL_HOST_LED_BIT, _CHIP, _CHANNELS: HID LED bit 1).

Usage: gen_v65v3_leds.py <table.bin> <out: boards/cidoo/cidoo_v65v3/led_driver_table.h>
"""
import sys

ROWS, COLS, CHANNELS = 8, 15, 192
NOTICE = (2, 0)  # Tab
CAPS = (3, 0)    # Caps Lock: the host's Caps Lock (HID LED bit 1)

img = open(sys.argv[1], "rb").read()
chan = [[0] * CHANNELS for _ in range(2)]
notice = []
caps = []
leds = [0, 0]
for r in range(ROWS):
    for c in range(COLS):
        chip, red, green, blue = img[4 * (r * COLS + c):][:4]
        if chip not in (1, 2):
            continue
        leds[chip - 1] += 1
        for colour, ch in enumerate((red, green, blue), 1):
            assert chan[chip - 1][ch] == 0, (r, c, ch)
            chan[chip - 1][ch] = (c << 2) | colour
            if (r, c) == NOTICE:
                notice.append((chip - 1, ch))
            if (r, c) == CAPS:
                caps.append((chip - 1, ch))
assert len(notice) == 3 and len(caps) == 3
lines = ["/*",
         " * The V65 V3's LED wiring: for each of the two driver chips, what each of its 192 PWM",
         " * channels (page 1 registers 0-191) drives. Bits 1:0: 0 nothing, 1 the red, 2 the green,",
         " * 3 the blue of an LED; bits 5:2: the matrix column (0-14) of its key. 66 key LEDs: chip 1",
         f" * (selected by PA1) holds {3 * leds[0]} channels, chip 2 (PD5) {3 * leds[1]}. The notice LED is the",
         " * Tab key's (BL_NOTICE_LED). Generated by boards/cidoo/cidoo_v65v3/gen_v65v3_leds.py.",
         " *", " * SPDX-License-Identifier: GPL-3.0-or-later", " */", "", "#include <stdint.h>", "",
         f"#define BL_LED_CHANNELS {CHANNELS}",
         "#define BL_NOTICE_LED(chip, i) ((chip) == %dU && (%s))" % (
             notice[0][0], " || ".join(f"(i) == {ch}U" for _, ch in notice)),
         "/* The host's keyboard LED shown on a key: Caps Lock (HID LED report bit 1) on the Caps Lock key's",
         " * LED (row 3, column 0), chip %d's channels %d, %d and %d (red, green, blue) */" % (
             caps[0][0] + 1, *(ch for _, ch in caps)),
         "#define BL_HOST_LED_BIT      0x02U",
         "#define BL_HOST_LED_CHIP     %dU" % caps[0][0],
         "#define BL_HOST_LED_CHANNELS {%s}" % ", ".join(f"{ch}U" for _, ch in caps),
         "", "static const uint8_t bl_led_channel[2][BL_LED_CHANNELS] = {"]
for chip in range(2):
    lines.append("\t{")
    for i in range(0, CHANNELS, 16):
        lines.append("\t\t" + ", ".join(f"0x{v:02x}" for v in chan[chip][i:i + 16]) + ",")
    lines.append("\t},")
lines += ["};", ""]
open(sys.argv[2], "w").write("\n".join(lines))
print(f"chip 1: {leds[0]} LEDs, chip 2: {leds[1]}; notice channels {notice}")
